version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  client-app:
    image: websockets-kafka-demo_client-app:latest
    ports:
      - "3100:80"
    environment:
      - NODE_ENV=development
      - BACKEND_IP=${HOST_IP}
      - BACKEND_PORT=3102
  authentication:
    image: websockets-kafka-demo_authentication:latest
    command: bundle exec rails s -e production -p 80 -b '0.0.0.0'
    ports:
      - "3101:80"
  gateway:
    image: websockets-kafka-demo_gateway:latest
    command: bash -c "bundle exec karafka server --daemon && bundle exec rails s -e production -p 80 -b '0.0.0.0'"
    environment:
      - AUTHENTICATION_URL=http://authentication:80
      - PERFORMER_URL=http://performer:8080
    ports:
      - "3102:80"
  performer:
    image: websockets-kafka-demo_performer:latest
    restart: always
    environment:
      - GATEWAY_URL=http://gateway:80
    command: ["java",  "-jar", "/app.jar"]
    ports:
      - "3103:8080"


