#this file should not be under version control, this is for testing
PUBLIC_KEY:
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk6LLc0eT7dRhrsUy77Jo\
  +3/w+vpqC4cNK3ZWJFL2WA7EhQUz1YkdzjnMLbfsJFDwIlMP1jEY3/Q8GZetaMv3\
  3oOWczbj6Wv/eUApX7IM3L0ei0EZN9g60A5Wb9HsIAy3QJ8643J0D1YONaKFdqcn\
  uZaYpNKwduc0OUYM+CGH3QSN8gdfoKvZCFU/7bYvIQeK34ygAsjpywo5ymeRs8EC\
  MmQvZ11PW4RCCGkKgfNdRgkxOrcpDftCh4GJw2JeiBGfoqNAnfg63wjd07kdoDbu\
  bQ8Hb4ikE+BGVuGXtRgK+0jkiAzaGa/+btWnTl1HM5MEcwHDg91QpkFoMl/MfAT9\
  5QIDAQAB"
PRIVATE_KEY:
  "MIIEowIBAAKCAQEAk6LLc0eT7dRhrsUy77Jo+3/w+vpqC4cNK3ZWJFL2WA7EhQUz\
  1YkdzjnMLbfsJFDwIlMP1jEY3/Q8GZetaMv33oOWczbj6Wv/eUApX7IM3L0ei0EZ\
  N9g60A5Wb9HsIAy3QJ8643J0D1YONaKFdqcnuZaYpNKwduc0OUYM+CGH3QSN8gdf\
  oKvZCFU/7bYvIQeK34ygAsjpywo5ymeRs8ECMmQvZ11PW4RCCGkKgfNdRgkxOrcp\
  DftCh4GJw2JeiBGfoqNAnfg63wjd07kdoDbubQ8Hb4ikE+BGVuGXtRgK+0jkiAza\
  Ga/+btWnTl1HM5MEcwHDg91QpkFoMl/MfAT95QIDAQABAoIBACHG8ykyzSNync6w\
  i1DPzrkLsoSZWj287kRtVJQG7xmCd2+/mvZV4p3WF2K2W66LXgVcX5kvrnM+m6l3\
  TFNXpyQfkwJVIpu6+74v8cdVIyA1nJFbmXtvWzVSsm/u5UkH371HMN/sxaTkmWeo\
  AUT+RVZuoAnFsl3h087uufTjJwRntGpTclulmQWBdQ3OcYFOccTrSk+/rlDSsPla\
  HNqzNFptvi33w0bZuMykhQhozk4gFLEPsG/aH/8AS5a/I3QMRPxgAuiZFKnFkNNL\
  +u8BRDwEkottEvetfZkAQorQW++b4PU5AXrtY1ULWBAMDXArOQXwDfG7GBJYLMyL\
  megcORkCgYEA+6Y4w/oDcMkVArxqWyfPyKXV7sxTC9yIdLfiIzLR+dAmHIF0j6+C\
  R20DJuJXkbrGtYiUxjKWweL2xB8sToHDasxfNlIYukUxhbD+mSniD3FFi20vleb2\
  CJtL3u1RzmCi7VoY3YgDD0ta+GG0KwG/WPVIUbE/pMh0ANRyI9ItW4cCgYEAljA3\
  +VTpI3TJBbddqh0SsNsBhXyh8xgdak8UVVLM1WiXmMsa0jQIRJjqufuAOezhHbzr\
  E5wTEITZRBHpvZuRFSv1LEMhsRv4shknVweoX5fksKE0yNgexYbmAllLH8AcV+7r\
  GKxUWjdXWz2WRRCXLNqwMVtbXHv3jkg8+X6KrjMCgYAEsjJm/dhol2gL+AYoE1Me\
  VHHsleWK2B+3xeKzc3RVrBu59nR9ZfIRcShY5mpp7slcg+L62+DSV3Dxcf96q5NA\
  //Va5ydM+pOVAhuOMijkzuFUW8JCkt/Og09kJpubNVR1B3RlVe9wrqBQ+EnLb6np\
  eBJUa/FbGt6HUW+b2YU9KwKBgFTzpVWlD9J8ZpCTLanhlAbxeiTVYI2uoETXwjqZ\
  AT/dT5Kfn+YyhFK45Fyaw+b/9D3r9FQ9PhNj8bktILedXS1Klf2ZY19Y4Q1saPIz\
  ZKvdsP+vz7mjdZRpP4UomPO2qNGcVOK552S4VPNJHMyoG7rFYFAqyry/akHS3pqJ\
  V0w9AoGBAIZre/KB4pWF0BPnYVs5RBwbvn5TvP20Y9Gey/Lu49XJQpWwwXDltxaz\
  hbeSDRl8RphD+KLRs4yQZnx8aEyPBpTm0g0NUC3VlCn3eEIjdtXQppqdSrvoI4AV\
  JoVsk++v1GrMsPcWe8orO7/1QYMJPzIa0OmiWB3q5AS3tj/dKVmw"

