authentication_service: <%= ENV['AUTHENTICATION_URL'] %>
performer_service: <%= ENV['PERFORMER_URL'] %>
#client_app: <%= ENV['CLIENT_APP_URL'] %>

#authentication_service: http://localhost:3001
client_app: http://localhost:3000
#performer_service: http://localhost:8080
